### PR TITLE
Change SAM's default zoom level to zero

### LINKED ISSUE #176: Default zoom level should be zero, not 4
Ideally, all data for a study or megastudy should appear in the user's initial viewport, no matter how big their screen is.

This is because the default behaviour of the map is to "fly to" the best-fit view of the marker data shown in the initial default viewport.

For some reason the default is 4, but zero should work better.

### PR DESCRIPTION
**Pull request by bobular**
Resolves #176 

Related to #144

### CODE REVIEW

**Review by moontrip — COMMENTED** [review]
Hi @bobular Actually I left a comment https://github.com/VEuPathDB/web-monorepo/issues/176#issuecomment-1540381056.

Another comment is that zoom: 0 is too small for me perhaps because I am using 4k monitor. 

I briefly zoom: 0 with the custom zoom control, but somehow zoom to data does not work in that case. It works from zoom: 1. I don't know why right now.

- zoom: 0
zoom-zero

**Comment by bobular** [comment]
No 4k monitor here, but testing with zoom=0 in https://github.com/VEuPathDB/web-monorepo/pull/137 works fine for me (dfalke-b back end and SCORE S. mansoni).

Can you describe what happens on your screen?

**Comment by bobular** [comment]
PS. I'm happy to close this without merging if you make the change in your branch.

**Comment by moontrip** [comment]
> No 4k monitor here, but testing with zoom=0 in #137 works fine for me (dfalke-b back end and SCORE S. mansoni).
> 
> Can you describe what happens on your screen?

@bobular When I pressed zoom-to-data icon, it went to [0, 0] with zoom of 0 and did nothing since then. FlyTo works when zoom >= 1

**Comment by bobular** [comment]
Converted to draft. Revisit and close/fix as necessary.

**Comment by bobular** [comment]
Closed as won't fix

**Pull request closed without merging**
