### PR TITLE
Use webpack 5 for sites packages

### PR DESCRIPTION
**Pull request by dmfalke**
### Description

This PR upgrades the version of webpack used for local dev sites to v5, mostly following [this guide](https://webpack.js.org/migrate/5/). I also enabled filesystem cache, which improves incremental builds.

~I may also explore different ways to make watch mode work better when files in other packages change.~

I have made some improvements to watch mode: ensuring that changes to src files do not trigger a rebuild, and ensuring that we don't get successive webpack rebuilds based on running `build-npm-modules`.

### Testing

The following list describes the testing I have done on this PR.

- [x] Run `yarn nx start ...` for each site package
  - [x] clinepi-site
  - [x] genomics-site
  - [x] mbio-site
  - [x] ortho-site
- [x] Run `yarn nx bundle:dev ...` for each site package
  - [x] clinepi-site
  - [x] genomics-site
  - [x] mbio-site
  - [x] ortho-site
- [x] Run `yarn nx bundle:npm ...` for each site package
  - [x] clinepi-site
  - [x] genomics-site
  - [x] mbio-site
  - [x] ortho-site
- [x] Push bundles from `bundle:dev` to dev site for each site package
  - [x] clinepi-site
  - [x] genomics-site
  - [x] mbio-site
  - [x] ortho-site
- [x] Push bundles from `bundle:npm` to dev site for each site package
  - [x] clinepi-site
  - [x] genomics-site
  - [x] mbio-site
  - [x] ortho-site
- [x] Test cache invalidation by updating src code in a lib package and rerunning `bundle:dev`

### CODE REVIEW

**Comment by dmfalke** [comment]
Just realized I need to update `peerDepenencies` in `base-webpack-config`.

**Comment by jernestmyers** [comment]
> Just realized I need to update `peerDepenencies` in `base-webpack-config`.

Okay, I'll wait to test then. I haven't had any luck spinning up a site dev server.

**Comment by dmfalke** [comment]
> Okay, I'll wait to test then. I haven't had any luck spinning up a site dev server.

I've updated peerDependencies. Maybe we can take a look at why it isn't working for you, together.

**Comment by dmfalke** [comment]
I think this is ready for review now!

**Review by jernestmyers — APPROVED** [review]
LGTM! I only tested the `sites` dev servers, all of which spun up fine. I also ran a couple `bundle:dev` builds that also ran without issue.

**Pull request merged**
