### PR TITLE
Take a less agressive path when requesting user datasets from within eda

### PR DESCRIPTION
**Pull request by dmfalke**
This PR removes a code path that causes an error to be thrown, in favor of a conditional statement, for requesting user datasets within eda.

Resolves this error

```
ERROR
In order to use this feature, a VdiCompatibleWdkService must be configured.
```

### CODE REVIEW

**Review by bobular — APPROVED** [review]
LGTM. I'm not familiar with the bug this resolves but we're definitely not throwing an exception any more from `assertIsVdiCompatibleWdkService`

**Comment by bobular** [comment]
> This addresses a bug you reported when running the `start` command for `@veupathdb/eda` 😄

Guess I'd better test that then!

**Comment by bobular** [comment]
libs/eda dev server works for me but see https://github.com/VEuPathDB/web-monorepo/pull/1195 (I needed this too)

**Comment by dmfalke** [comment]
> libs/eda dev server works for me but see #1195 (I needed this too)

ok, will look!

**Pull request merged**
