### PR TITLE
Refactor OrthoMCL's Sequences table to enable Mesa's selection column

### LINKED ISSUE #1148: OrthoMCL - Group page "List of All Protein" - Checked checkbox state is reset when table filter changes
To reproduce:

- Go to https://orthomcl.org/orthomcl/app/record/group/OG6_100778#Sequences
- Select first row of table
- Type "pfal" in filter box
- Clear filter box
- See that first row of table is no longer selected

Note that we will likely want to patch the live site.

### PR DESCRIPTION
**Pull request by jernestmyers**
Resolves #1148

A couple notes:
1. I don't have an ortho dev site to run these changes on to ensure the actual POST works, but it's wired up very similarly to the genomics version that works.
2. I can make the model change to change the isDisplayable flag (or whatever it's actually called in the XML) of the clusterInput column if you think it's worth doing; again, not sure what the future of this UI is with respect to the tree diagram.

### CODE REVIEW

**Comment by dmfalke** [comment]
> I can make the model change to change the isDisplayable flag (or whatever it's actually called in the XML) of the clusterInput column if you think it's worth doing; again, not sure what the future of this UI is with respect to the tree diagram.

I would make the least amount of changes possible, imho.

Regarding not being able to test, I can build my dev ortho site with this branch. It will be sometime this afternoon.

**Review by dmfalke — APPROVED** [review]
:rocket:

**Comment by bobular** [comment]
Hi @dmfalke and @jernestmyers - can we meet to discuss how this affects my orthogroup-tree-table PR https://github.com/VEuPathDB/web-monorepo/pull/904 which is currently deployed on qa.orthomcl.org ?

**Comment by dmfalke** [comment]
> Hi @dmfalke and @jernestmyers - can we meet to discuss how this affects my orthogroup-tree-table PR #904 which is currently deployed on qa.orthomcl.org ?

It should not impact your branch. You should ignore the changes to `Sequences.jsx` when merging this in. I'm happy to help with that.

**Pull request merged**
