### PR TITLE
Stop map markers occasionally disappearing at minimum zoom

### PR DESCRIPTION
**Pull request by bobular**
Fixes https://github.com/VEuPathDB/web-components/issues/352 again!

### CODE REVIEW

**Comment by bobular** [comment]
Hmm, not 100% sure about my logic here!

**Comment by bobular** [comment]
It's very difficult to reproduce the bug.  But keep zooming out and it should happen (but not on this branch).

**Comment by moontrip** [comment]
@bobular When I saw your first commit, I  wondered the same thing using the absolute value of the difference, which was applied in later commit 👍

**Review by moontrip — APPROVED** [review]

**Comment by bobular** [comment]
Thanks DK!

**Pull request merged**
