### PR TITLE
Timeslider help icon and further slimming

### PR DESCRIPTION
**Pull request by bobular**
Note merge into parent branch

image

### CODE REVIEW

**Review by jernestmyers — COMMENTED** [review]
Yikes, this is a tough UX/UI to work out.

I think I'd prefer the help icon to be with the on/off toggle, but then that dramatically affects the layout. I like its size in this iteration, though I wonder if folks are okay with the time filter not showing the selected variable?

**Comment by bobular** [comment]
> Yikes, this is a tough UX/UI to work out.
> 
> I think I'd prefer the help icon to be with the on/off toggle, but then that dramatically affects the layout. I like its size in this iteration, though I wonder if folks are okay with the time filter not showing the selected variable?

A textless on/off toggle could go in the minimized version perhaps?

**Comment by jernestmyers** [comment]
> > Yikes, this is a tough UX/UI to work out.
> > I think I'd prefer the help icon to be with the on/off toggle, but then that dramatically affects the layout. I like its size in this iteration, though I wonder if folks are okay with the time filter not showing the selected variable?
> 
> A textless on/off toggle could go in the minimized version perhaps?

If so, we'd maybe want the toggle's status at the top of the tooltip. I wonder how much wider the component gets with the toggle and tooltip next to the slider. 🤔

**Comment by bobular** [comment]
Why not "textless"/no status label?

Otherwise it gets very wide

**Comment by bobular** [comment]
I'm thinking that the on/off toggle is not core functionality - it's for the specific case where you want to toggle between time-sliced and not time-sliced. I think it's OK to live only in the expanded version?

**Comment by bobular** [comment]
Why can I merge this without an approval?

**Comment by jernestmyers** [comment]
> Why can I merge this without an approval?

I'm guessing because you're requesting to merge this into a branch that isn't `main`.

**Comment by bobular** [comment]
> > Why can I merge this without an approval?
> 
> I'm guessing because you're requesting to merge this into a branch that isn't `main`.

Oh duh...
Nice work, Columbo!

**Pull request merged**
