### PR TITLE
introducing scientific notation for histogram stats and plot

### PR DESCRIPTION
**Pull request by moontrip**
This will resolve https://github.com/VEuPathDB/web-eda/issues/1677 (stats) and https://github.com/VEuPathDB/EdaNewIssues/issues/603 (plot). Currently significant figures are set to be 5.

A screenshot is attached here (same example used at https://github.com/VEuPathDB/web-eda/issues/1677#issuecomment-1454240302 is utilized here for a better comparison):

histogram-filter-segnis1

### CODE REVIEW

**Comment by moontrip** [comment]
Hi @asizemore, I am asking your review because you initiated the tickets 😃 
I think that when you run `@veupathdb/eda`, then you may need to do `yarn build-npm-modules` at `@veupathdb/components` because of the change at @veupathdb/components for plot

**Review by asizemore — APPROVED** [review]
looks good! Since there was some logic around years removed, it'd be helpful for whoever qa's this to check how it works for any variable with years that are not dates (not sure if we have any of those, but just in case :) )

**Comment by moontrip** [comment]
@asizemore Thank you for your reviews and tests.  Yes there may be a year variable but I cannot remeber those variables. I will check it out if possible, and see how it works. 👍

**Comment by moontrip** [comment]
@asizemore I found one variable that has year format: I may alleviate the case if not perfect. But one question to you is how to handle the mean value of the year. Is it okay to round up? e.g., if 2003.11881231231, then 2003? Or do you want to have a decimal points for that like 2003.12?

**Comment by moontrip** [comment]
@asizemore Thank you for sharing your opinion. I made an adjustment to minimize the effect of year variable by checking type: integer, value >= 1900 & <=2100 which is not perfect but may work in most cases. At Live site, I noticed it uses 4 decimal points for the mean stats of the year so I followed it. Here is a screenshot after this change. Plot is fine without further change as the year number has 4 digit so scientific notation is not used in this case.

Amazonia ICEMR Brazil Cohort year variable1

**Pull request merged**
