### PR TITLE
modifying correlation inputs

### PR DESCRIPTION
**Pull request by moontrip**
This will address https://github.com/VEuPathDB/web-monorepo/issues/832.

For the last item to fix a bug or change behavior, honestly, I could not fully understand how the computation worked, but I managed to make it fix anyway 😅 

Some screenshots after changing:

832 mbio correlation01

832 mbio correlation02

### CODE REVIEW

**Comment by moontrip** [comment]
> Looking great! One small request - can we make the text "Keep ... in at least" and "% of samples" in normal casing (somehow there has been a `capitalize` text-transform applied) and in regular font weight please? In other words, for both apps, everything after "Prevalence" should be regular, non-bold weight and regular capitalization without transform.
> 
> Otherwise it looks and works great! I am so happy to have that input working correctly 😄

Thank you for your review and suggestion @asizemore 👍 Yes I also noticed the capital characters at each word, which is probably a CSS. I will change it and make screenshots to confirm :)

**Comment by moontrip** [comment]
Done @asizemore Please check below screenshots:

832 mbio correlation03

832 mbio correlation04

**Comment by asizemore** [comment]
gorgeous!

**Review by asizemore — APPROVED** [review]
lgtm!!

**Pull request merged**
