### PR TITLE
105-map-logo

### LINKED ISSUE #105: Standalone map: figure out easily configurable site icon when deploying on different sites
This is for the top left icon in the header panel.

Phase X

It would be good if when deploying to different sites (e.g. VectorBase, Plasmo, ClinEpi, MBio) that we don't have to store the icons within the app source itself.

### PR DESCRIPTION
**Pull request by dmfalke**
**Before**
image

**After**
image

### Description

Fixes #105

This PR cleans up some files from the `webapp` directory of site packages, and copies all deployable assets to `dist` when the `bundle` scripts run. It also updates `siteInformationProps` passed to the map app.

I removed a lot of files that erroneously got copied into this repo, in this PR. The most relevant commit is https://github.com/VEuPathDB/web-monorepo/pull/109/commits/b5680930236d720a7d8ce35425b48f3fffa320b0, which updates the `/maps` route to include better `siteInformationProps` values.

### Testing

The best way to fully test this PR is to:

1. Build a dev site
2. Run `yarn nx bundle:dev $sitePackage`
3. Run `rsync -rvz  packages/sites/$sitePackage/dist/* $server:$targetWebappDir`

I've done this already with https://dfalke-b.clinepidb.org. If you go to https://dfalke-b.clinepidb.org/ce.dfalke/app/maps/DS_d6a1141fbf, and create a new analysis, you will see the clinepi logo in the map header. You can also use that site as a backend with a local dev site, to see the changes.

### CODE REVIEW

**Comment by adnauseum** [comment]
image

🙇 10X dev!

**Comment by dmfalke** [comment]
I'm anxious to get this merged, so I requested a review from @adnauseum 😁

**Comment by dmfalke** [comment]
Going rogue!

**Comment by bobular** [comment]
Oh, sorry, I just got to this. I'll have a look over so I understand what you did.

**Pull request merged**
