### PR TITLE
Markers automatically use the most appropriate geoEntity when there are multiple to choose from

### LINKED ISSUE #1024: Make studies with more than one geo-located entity work on the SAM
This only concerns **Transmission Zero Field Trials**, on qa.restricted.clinepi. It has four entities with lat/long/geohashes. A root entity (which was previously the only entity being 'mapped') and its three children.

Before this PR, everything was shown at the center of the geohash_4 grid.

Now, if you pick variables from any of the non-root entities, the markers will be shown at the position of the appropriate entity, not the artificial root entity.

### PR DESCRIPTION
**Pull request by bobular**
Fixes #1024 

This only affects the Transmission Zero Field Trials prototype dataset at the moment (qa restricted clinepi) because this is the only study where more than one entity has geo variables.

Luckily a lot of the code was already passing around `geoConfigs` rather than `geoConfigs[0]` so there wasn't a huge amount of upheaval.

I have implemented this as if there was a drop-down for the user to choose the geoEntity they wanted, but instead have chosen the least ancestral entity for them automatically. So this is why this "choice" is stored in appState. We can add UI later if needed.

- [x] Donut mode
- [x] Bar mode
- [x] Bubble mode

### CODE REVIEW

**Comment by dmfalke** [comment]
I'm having trouble remembering how this will manifest in the UI. Where will I see a change in behavior?

**Comment by bobular** [comment]
> I'm having trouble remembering how this will manifest in the UI. Where will I see a change in behavior?

The only study with multiple geo-entities (geoConfigs) is Transmission Zero Field Trials, so for every other study this PR is a 'no op' - all the logic returns `geoConfigs[0]`

If you compare qa.restricted.clinepi with this PR you'll see that when you pick an adult entomology sample variable like "Morphological species ID" the locations are different. In the main branch, only the root entity locations are used for markers. In the PR, the closest entity to the chosen variable is used.

**Comment by dmfalke** [comment]
Ah, okay! So it only impacts location? Anyway, this looks great to me so far. I will test w/ the mega study, just to be sure.

**Comment by bobular** [comment]
I realised I didn't do the other marker modes yet. Doing now!

**Comment by dmfalke** [comment]
> I realised I didn't do the other marker modes yet. Doing now!

:smile: 

On that note, I'm primarily looking for fatal errors. I think we need to rely on data experts for a more robust qa on this update.

**Comment by bobular** [comment]
I am the data expert on this study...

**Comment by dmfalke** [comment]
> I am the data expert on this study...

I know :smile:

**Review by dmfalke — APPROVED** [review]
Changes look good. Nothing appears broken. :rocket:

**Comment by bobular** [comment]
Added an issue to help with QA. Merging now. Thank you!

**Pull request merged**
