### PR TITLE
Add message for no data in volcano plot

### PR DESCRIPTION
**Pull request by chowington**
Closes https://github.com/VEuPathDB/web-monorepo/issues/808

Most of the diff is just indentation!

### CODE REVIEW

**Review by asizemore — APPROVED** [review]
lgtm!

**Comment by dmfalke** [comment]
I may be wrong, but isn't this different than how we handle empty data in other vizs? Eg, https://github.com/VEuPathDB/web-monorepo/pull/826

**Comment by asizemore** [comment]
Huh. You're totally right. For the network the user could do something about the no data, so it made sense to give them a message. But this volcano viz getting no data is just like any other plot getting no data. I had my mbio-app blinders on! Good call, @dmfalke . 
The other vizs just show the red banner saying something like "no plottable data". That makes sense here, too.

Sorry @chowington that's my fault!

**Review by asizemore — APPROVED** [review]
lovely! Works great! Thanks for handling the changeup @chowington !

**Pull request merged**
