### PR TITLE
Add collapsible section to studies menu

### PR DESCRIPTION
**Pull request by jernestmyers**
Resolves https://github.com/VEuPathDB/web-monorepo/issues/553

~~NOTE: This has not been added to mbio's menu. Awaiting review before doing so.~~

UPDATE: This has now been added to mbio's menu as well.

https://github.com/VEuPathDB/web-monorepo/assets/69446567/8ed1e6b6-6aa1-40ac-bb19-0fd0221ed41f

### CODE REVIEW

**Review by dmfalke — COMMENTED** [review]
This looks great. Implementation looks great. There is a voice in my head saying that we should use a native `<details>` element... you know, leverage the platform and all. Thoughts?

**Comment by jernestmyers** [comment]
> This looks great. Implementation looks great. There is a voice in my head saying that we should use a native `<details>` element... you know, leverage the platform and all. Thoughts?

I ran into issues with styling `<details>` elements in the past, but a quick read on MDN suggests I **_shouldn't have_**...

We also have `CollapsibleSection` in WDKClient, which I opted against due to a prior memory of limitations (without recollection of _**what**_ limitations)...

**Comment by dmfalke** [comment]
Fair enough!

**Comment by dmfalke** [comment]
This looks great, but I think curated studies should default to open. I suspect clinepi outreach would prefer that.

**Review by dmfalke — APPROVED** [review]
:rocket:

**Pull request merged**
